- src/Makefile
- src/ocaml/plugin/extract-pulse.Makefile
- src/ocaml/plugin/extract-steel.Makefile
So far `make -C src full-boot` removes the whole snapshot and rebuilds it from scratch in a staged way: verifying and building the Steel tactic, then verifying Steel, then verifying and building the Pulse checker.
But this model will no longer work as soon as handwritten files depending on other extracted files (say Pulse) are added to `src/ocaml/plugin`, as requested by @nikswamy 
Thus, this PR refactors the bootstrap process by making it more similar to what is done in F*: with this PR, `make -C src full-boot`  will first build the snapshot as it is, and then verify Steel and Pulse with that snapshot, and then re-extract everything.
The CI will still make sure that all files are still consistent in this process.
> Bootstrap using the current snapshot (no longer from scratch)

- Makefile
- flake.nix
- src/c/Makefile
This PR does three different things:
- first, it adds a new required dependency to build Steel using Nix (menhir) ;
- second, it improves the install target : previously, src/c/*.c files, that is src/c/steel_spinlock.c, were not installed, leading to CI failures ;
- third, it adds a new subderivation that allows to only build Steel when this is all that is required (e.g. for a CI job).
Marking it as WIP while checking for INRIA's CI result.
Supersedes #7 for mergeability reasons.
As pointed out by @tahina-pro, the updated install targets installs src/c/*.c files. The reason is that when working on a Steel project that yields C code through KaRaMeL, it is better to have source .c files, that is, to have a final compilation phase that only require .c files (extracted ones and source ones …
> Nix: fix build

- Makefile
- flake.nix
- include/steel/steel_base.h
- lib/steel/Steel.ArrayArith.fsti
- src/c/Makefile
Depends on  #9 .
The so-far used model and implementation of within_bounds_ptr are not very natural. That is, when checking whether a pointer belongs to an array, which is the main use case of within_bounds_ptr, one wants to have a strict upper check, which otherwise would lead as currently to a possible off-by-one error.
Indeed, given an array arr,  `split_r arr (A.length arr)` is a Steel array of length zero, which cannot be accessed.
This PR is thus a fix for this case.
> Steel: improve within_bounds

- lib/steel/Steel.ST.HigherArray.fsti
This PR does minor tweaks to the implementation of the array accesses and updates to improve the quality of extraction.
Concretely, it uses the inlining ptr_of predicate instead of deconstructing the pointer pair inside index and upd. This avoids an extra let-binding of the shape `let pt = a in ...` when extracting memory accesses and updates.
Note, I initially tried adding an inline_let on the previous `let (| ptr, len |) = a in`, but this did not yield the expected behavior.
> Better extraction for array primitives

- lib/steel/Steel.ST.Array.Swap.fst
- lib/steel/Steel.ST.Array.Swap.fsti
- lib/steel/Steel.ST.GenArraySwap.Proof.fst
- lib/steel/Steel.ST.GenArraySwap.fst
- lib/steel/Steel.ST.GenArraySwap.fsti
- share/steel/examples/pulse/ArraySwap.fst
- share/steel/tests/krml/ArraySwap.fst
Let `a` be an array of size `n`, and let `0 < l < n`. How do we swap the regions from `0` to `l-1` and from `l` to `n-1` of `a`?
With @mtzguido , we have been working on a verified implementation performing this task **fully in-place** and in only `n` writes.
To do that, we compute the gcd of `n` and `l`, say `d`, so that any array index `x` can be reached from some `i` such that `0 <= i < n` by repeatedly adding `l` and truncating modulo `n`, and such starting point `i` is unique for a given `x`.
Then, for each such `i`, we save the contents of `a[i]`, then we shift `a[(i+l)%n]`, `a[(i+2l)%n]`, etc. to `l` positions to the left (treating `a` as a "ring buffer"), and we do it `n/d - 1` times, and then we restore the saved contents to the last index of that cycle.
The proof involves:
* …
> Swapping two adjacent regions of an array of any sizes

- src/ci/ci.Dockerfile
- src/ci/hierarchic.Dockerfile
- src/ci/no-fstar-home.Dockerfile
Installing dependencies (some of them, the ones we know a priori) before
the ADD helps with the build being cached up to that point. Since the
ADD adds every file in the repo, including potentially the git history,
any change whatsoever invalidates the cache for every step that follows.
> ci: shuffle dockerfiles a bit

- src/ocaml/plugin/generated/Pulse_Main.ml
- src/ocaml/plugin/generated/Steel_Effect_Common.ml
- src/ocaml/plugin/generated/Steel_ST_GenElim1_Base.ml
- src/ocaml/plugin/generated/Steel_ST_GenElim_Base.ml
This is needed to not break the build after FStarLang/FStar#3001 is merged. The plugin registration calls now take a string that will be displayed on error contexts.
> snap for FStarLang/FStar#3001

- share/steel/examples/pulse/Makefile
Looks like just an omission, setting for automerge.
> examples/pulse/Makefile: include current directory too

- lib/steel/pulse/Pulse.Checker.Prover.Match.fst
- src/ocaml/plugin/generated/Pulse_Checker_Prover_Match.ml
The match step in the prover gets a query of the form: `match p q` where, `p` is an atomic vprop in the context and `q` is an atomic vprop in the precondition of the stateful command. `q` may have uvars for logical variables. The output of the step is a substitution for the uvars such that `p` and `q` are equivalent.
This PR tweaks the step a little bit to disentangle the unification and equivalence checking. Earlier the two were interleaved, causing a lot of inefficiencies in terms of unnecessary, failing smt queries. Basically, if `p` and `q` are function calls, then recursing on head of `p` and head of `q` makes the heuristic of when to use smt much more relaxed.
The fix is to do it in two steps: first infer all the uvars, this is a structural pass over `p` and `q` and builds a …
> A tweak to the matching step in the prover

- lib/steel/pulse/Pulse.Main.fst
- src/ocaml/plugin/generated/Pulse_Main.ml
The F* PR above will allow reflection primitives to raise guards that are tracked in the proofstate. By default, these are stored as SMT goals, which changes the current behavior which is to just solve them on the spot. This patch is meant to ensure this behavior is retained until #65 is merged.
This shouldn't incur any functional change.
> Prepare for FStarLang/FStar#3001

- lib/steel/Steel.ST.Array.fsti
- lib/steel/Steel.ST.HigherArray.fsti
- share/steel/examples/pulse/dice/engine/EngineCore.fst
The explanation for the steel fixes is in the F* PR (https://github.com/FStarLang/FStar/pull/3004).
The Pulse breakages are due to some type conversions under `Ghost.erased`. But those implicit annotations are not needed anyway, so ended up removing these.
> Fixes for F* PR #3004

- lib/steel/pulse/Pulse.Checker.Prover.Match.fst
- lib/steel/pulse/Pulse.Config.fst
- lib/steel/pulse/Pulse.Config.fsti
- lib/steel/pulse/Pulse.Main.fst
- lib/steel/pulse/Pulse.Typing.Util.fst
- lib/steel/pulse/Pulse.Typing.Util.fsti
- share/steel/examples/pulse/ArrayTests.fst
- src/ocaml/plugin/generated/Pulse_Checker_Prover_Match.ml
- src/ocaml/plugin/generated/Pulse_Config.ml
- src/ocaml/plugin/generated/Pulse_Main.ml
- src/ocaml/plugin/generated/Pulse_Typing_Util.ml
This is based on https://github.com/FStarLang/FStar/pull/3011. With that change, F* will now treat the guards generated during Reflection.Typing primitive calls as Meta-F* guards, which can be pushed as SMT goals (the default), solved synchronously with SMT, without SMT, etc.
Keeping guards as (separate) SMT goals is the default. This PR joins them all into a single goal at the end of the checker run, to economize on Z3 calls. 
These merged goals can clearly require more solvers resources to be proven, so there's a question of what to do with the rlimit. I wrote some heuristic that increases the rlimit when merging goals... but it'd be good to find something more principled.
Note: CI will likely be green but it's running against F* previous to merging PR …
> Query aggregation

- lib/steel/pulse/Pulse.Main.fst
- src/ocaml/plugin/generated/Pulse_Main.ml
Example (deleting the dot after `invariant`).
Before, only a pointer to the pulse header (though the actual range is printed inside of that diagnostic)
After, highlighting on the source:
> Pulse: keep the range on syntax errors

- lib/steel/pulse/Pulse.Checker.Bind.fst
- lib/steel/pulse/Pulse.Checker.Pure.fst
- lib/steel/pulse/Pulse.Checker.Pure.fsti
- lib/steel/pulse/Pulse.Typing.fst
- src/ocaml/plugin/generated/Pulse_Checker_Bind.ml
- src/ocaml/plugin/generated/Pulse_Checker_Pure.ml
- src/ocaml/plugin/generated/Pulse_Typing.ml
Without this, any kind of complex type in an annotations would fail, as the check was being done over unelaborated terms.
> Pulse: elaborate annotations before check_universe

- src/ocaml/plugin/generated/PulseDesugar.ml
Needed due to FStarLang/FStar#3032 which introduced a new field to the TC environment.
> snap, fix for F* patch

- share/steel/examples/pulse/GhostStateMachine.fst
- share/steel/examples/pulse/lib/Pulse.Lib.Core.fst
- share/steel/examples/pulse/lib/Pulse.Lib.Core.fsti
- share/steel/examples/pulse/lib/Pulse.Lib.GhostReference.fst
- share/steel/examples/pulse/lib/Pulse.Lib.GhostReference.fsti
- share/steel/examples/pulse/lib/Pulse.Lib.HashTable.fst
- share/steel/examples/pulse/lib/Pulse.Lib.HigherReference.fst
- share/steel/examples/pulse/lib/Pulse.Lib.HigherReference.fsti
- share/steel/examples/pulse/lib/Pulse.Lib.Reference.fst
- share/steel/examples/pulse/lib/Pulse.Lib.Reference.fsti
- Make sure all three flavors of references have share, gather, and
pts_to_eq_injective exposed and implemented.
- Introduce the `one_half` permission in Pulse.Lib.Core, equal to
`half_perm full_perm`.
- Also implement share2/gather2 for the common case of splitting a
full_perm into halves and then joining back. This is useful
as Pulse does not yet automate permission arithmetic.
> Pulse: References: exposing uniform pts_to_injective_eq, share, gather

- lib/steel/Steel.Effect.Atomic.fst
- lib/steel/Steel.Effect.Atomic.fsti
- lib/steel/Steel.Memory.fst
- lib/steel/Steel.Memory.fsti
- lib/steel/Steel.ST.Util.fst
- lib/steel/Steel.ST.Util.fsti
When allocating an invariant, it is useful to know that the new invariant is distinct from all other allocated invariants.
While we don't yet have a way to refer to the universe of all allocated invariants, we can allow the caller to pass in the set of invariants and ensure that the newly allocated invariant is distinct from all of them.
I've added a `fresh_invariant` in Steel.Memory, and propagated it to Steel.Effect.Atomic and Steel.ST.Effect.Atomic
Here is its signature in Steel.ST.Effect.Atomic
```fstar
let fresh_inv (e:inames) (ctxt:list pre_inv) #p (i:inv p) =
not (mem_inv e i) /\
(forall qi. List.Tot.memP qi ctxt ==> name_of_pre_inv qi =!= name_of_inv i)
val fresh_invariant (#opened_invariants:inames) (p:vprop) (ctxt:list pre_inv)
: STAtomicUT (i:inv p {fresh_inv opened_invariants …
```
> Fresh invariant

- lib/steel/pulse/Pulse.ASTBuilder.fsti
- lib/steel/pulse/Pulse.Main.fst
- src/ocaml/plugin/Pulse_Parser.ml
- src/ocaml/plugin/generated/PulseDesugar.ml
- src/ocaml/plugin/generated/Pulse_ASTBuilder.ml
- src/ocaml/plugin/generated/Pulse_Main.ml
- src/syntax_extension/Pulse.Parser.fsti
- src/syntax_extension/PulseDesugar.fst
- src/syntax_extension/PulseDesugar.fsti
- src/syntax_extension/Pulse_ASTBuilder.fst
This fixes desugaring errors to only highlight the offending location, coming from F*. Instead of adding another error saying "Failed to desugar Pulse term", we just add that string to the context of the error we got back from F*. This is especially useful when a typo is made inside a big F* term within Pulse.
Before (here there are two overlapped errors. Hovering over `fb` will print the correct "Identifier not found" message, but there's no visual indication):
After:
> Making desugaring errors more localized

- lib/steel/pulse/Pulse.Checker.Pure.fst
- share/steel/examples/pulse/lib/Pulse.Lib.GhostReference.fst
- share/steel/examples/pulse/lib/Pulse.Lib.GhostReference.fsti
- share/steel/examples/pulse/lib/Pulse.Lib.Pervasives.fst
- src/ocaml/plugin/generated/Pulse_Checker_Pure.ml
Plus, add a `perform` to Pulse.Lib.Pervasives, as we commonly need to use it.
> Treat ghost refs as non-informative

- lib/steel/pulse/Pulse.Checker.Prover.fst
- lib/steel/pulse/Pulse.Config.fst
- lib/steel/pulse/Pulse.Config.fsti
- lib/steel/pulse/Pulse.PP.fst
- lib/steel/pulse/Pulse.RuntimeUtils.fsti
- lib/steel/pulse/Pulse.Show.fst
- lib/steel/pulse/Pulse.Syntax.Printer.fst
- lib/steel/pulse/Pulse.Syntax.Printer.fsti
- lib/steel/pulse/Pulse.Typing.Env.fst
- lib/steel/pulse/Pulse.Typing.Env.fsti
- src/ocaml/plugin/Pulse_RuntimeUtils.ml
- src/ocaml/plugin/generated/Pulse_Checker_Prover.ml
- src/ocaml/plugin/generated/Pulse_Config.ml
- src/ocaml/plugin/generated/Pulse_PP.ml
- src/ocaml/plugin/generated/Pulse_Show.ml
- src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml
- src/ocaml/plugin/generated/Pulse_Typing_Env.ml
This PR makes Pulse use the new error doc framework in F*, and improves the two most common errors with it: 'cannot prove vprop' and 'unmatched vprop in post'. See this example from `L0Crypto.fst`
Trying to free something twice:
Forgetting to free something:
> Pretty printing errors

- lib/steel/Steel.ST.Array.Util.fst
- lib/steel/pulse/Pulse.Class.BoundedIntegers.fst
These changes are needed to keep the build working after the F* PR is merged.
> Fixes for https://github.com/FStarLang/FStar/pull/3072

- lib/steel/pulse/Pulse.Checker.Abs.fst
- lib/steel/pulse/Pulse.Checker.Pure.fst
- lib/steel/pulse/Pulse.RuntimeUtils.fsti
- src/ocaml/plugin/Pulse_RuntimeUtils.ml
- src/ocaml/plugin/generated/Pulse_Checker_Abs.ml
- src/ocaml/plugin/generated/Pulse_Checker_Pure.ml
* Checking the annotation on a Pulse function would produce an F* term without ranges; add the source ranges to the elaborated arrow.
* In Pulse.Checker.Pure, if a callback to the typechecker already reports an error issue with a range, then do not report another error blaming the entire term used in the callback. Instead, just call T.fail (with an error message), which adds an error stub to the top of the Pulse function, rather than masking the more precise original error report.
> Improving error localization in typechecker callbacks

- lib/steel/pulse/Pulse.Checker.Base.fst
- lib/steel/pulse/Pulse.Checker.Base.fsti
- lib/steel/pulse/Pulse.Checker.Bind.fst
- lib/steel/pulse/Pulse.Checker.Return.fst
- lib/steel/pulse/Pulse.Checker.Return.fsti
- lib/steel/pulse/Pulse.Checker.fst
- lib/steel/pulse/Pulse.RuntimeUtils.fsti
- share/steel/examples/pulse/Fibo32.fst
- share/steel/examples/pulse/Recursion.fst
- share/steel/examples/pulse/bug-reports/BugHigherOrderApplication.fst
- share/steel/examples/pulse/lib/Pulse.Lib.LinkedList.fst
- src/ocaml/plugin/Pulse_RuntimeUtils.ml
- src/ocaml/plugin/generated/PulseDesugar.ml
- src/ocaml/plugin/generated/Pulse_Checker.ml
- src/ocaml/plugin/generated/Pulse_Checker_Base.ml
- src/ocaml/plugin/generated/Pulse_Checker_Bind.ml
- src/ocaml/plugin/generated/Pulse_Checker_Return.ml
- src/syntax_extension/PulseDesugar.fst
- src/syntax_extension/SyntaxExtension.fst.config.json
Instead of syntactic resolving stateful applications during desugaring, we now resolve it in a type-directed way, looking at the type of the head of an application node.
This means you no longer have to do awful things like `perform (fun _ -> f x)` to apply an argument `f` to `x`.
More examples in BugHigherOrderApplication. 
I made use of an OCaml-based callback into the typechecker, modeled after RTB.instantiate_implicits but more permissive, to sniff the type of the head of an application, even though looking up the type may result in unresolved universe instantiations. Universes don't matter to decide if an application is effectful or not.
Resolves part 3 of #54
> Nik type directed stapp

- lib/steel/Steel.TLArray.fst
- lib/steel/Steel.TLArray.fsti
- share/steel/tests/krml/SteelTLArray.fst
Steel.TLArray provides a module for top-level, const arrays.
While other array modules now use a size_t when indexing, TLArray still used the old approach, based on UInt32 indices. This PR fixes this.
> Use size_t arg for index in TLArray, similarly to regular arrays

- lib/steel/pulse/Pulse.Checker.Pure.fst
- lib/steel/pulse/Pulse.Checker.Pure.fsti
- lib/steel/pulse/Pulse.Checker.STApp.fst
- pulse2rust/src/Pulse2Rust.Rust.Syntax.fst
- pulse2rust/src/Pulse2Rust.Rust.Syntax.fsti
- pulse2rust/src/Pulse2Rust.fst
- pulse2rust/src/ocaml/generated/Pulse2Rust_Rust_Syntax.ml
- pulse2rust/src/ocaml/rust/src/lib.rs
- share/steel/examples/pulse/ArrayTests.fst
- share/steel/examples/pulse/CustomSyntax.fst
- share/steel/examples/pulse/ZetaHashAccumulator.fst
- share/steel/examples/pulse/dice/dpe/DPE.Messages.Parse.fst
- share/steel/examples/pulse/dice/dpe/DPE.fst
- share/steel/examples/pulse/dice/dpe/DPE.fsti
- share/steel/examples/pulse/dice/l0/L0Core.fst
- src/ocaml/plugin/generated/Pulse_Checker_Pure.ml
- src/ocaml/plugin/generated/Pulse_Checker_STApp.ml
They no longer need to be at the end, some examples: https://github.com/FStarLang/steel/commit/fe5b6159fc2549fbf081f54d846db64f161a47dc
> Remove restriction on logical implicits ordering

- share/steel/examples/steelc/Makefile
Will be needed if we merge FStarLang/FStar#3130 as it is right now. Commit message:
> After FStarLang/FStar#3130, F* will (by default) not run meta args in open contexts, breaking most SteelC modules.
>
> This seems to be very intended for, e.g., field_description_cons, which has no way of instantiating `fn` (when there's no expected type) without running the tactic. Setting this compat option makes everything work as before.
> SteelC: Use compat option for running meta args in open ctxs

- lib/steel/pulse/Pulse.Checker.Prover.fst
- lib/steel/pulse/Pulse.Checker.Prover.fsti
- lib/steel/pulse/Pulse.Checker.fst
- share/steel/examples/pulse/bug-reports/Bug137.fst
- share/steel/examples/pulse/lib/Pulse.Lib.ArraySwap.fst
- share/steel/examples/pulse/lib/Pulse.Lib.LinkedList.fst
- src/ocaml/plugin/generated/Pulse_Checker.ml
- src/ocaml/plugin/generated/Pulse_Checker_Prover.ml
To handle some unexpected behaviors noticed in https://github.com/FStarLang/steel/issues/137 and https://github.com/FStarLang/steel/pull/135.
> Eagerly unfold exists and pure from the context at the top of the checker

- Steel.fst.config.json
- share/steel/examples/pulse/Makefile
- share/steel/examples/pulse/Makefile.pulse.common
- share/steel/examples/pulse/Pulse.fst.config.json
- share/steel/examples/pulse/class/Pulse.Class.PtsTo.fsti
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.InvList.fst
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.InvList.fsti
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Par.Pledge.Simple.fst
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Par.Pledge.Simple.fsti
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Par.Pledge.fst
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Par.Pledge.fsti
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Trade.fst
- share/steel/examples/pulse/lib/pledge/Pulse.Lib.Trade.fsti
- share/steel/examples/pulse/parix/Async.fst
- share/steel/examples/pulse/parix/ParallelFor.fst
- share/steel/examples/pulse/parix/Promises.Examples3.fst
- share/steel/examples/pulse/parix/TaskPool.Examples.fst
- share/steel/examples/pulse/parix/TaskPool.fsti
- share/steel/examples/pulse/parix/UnixFork.fsti
This version of trades (and pledges) allows us to not rely on any suspect axioms, such as extracting an unobservable function from a proof of existence, or a reveal for erased with the unobservable effect.
Now, trades and pledges are only ghost steps, but they can still be indexed with a set of invariants (concretely an `invlist`: a heterogeneous lists of invariants and their vprops). The underlying ghost step of a trade/pledge expects all of the invariants to already be opened, and must restore them. Essentially, this is hoisting the opening of invariants _within_ the trade/pledge to their callsite, which makes things easier.
An added limitation of this approach is that trades/pledges will not be able to allocate invariants. I don't think this will be a problem (and it hasn't been …
> Implementing Trades as ghost steps, which preserve a given set of (already opened) invariants

- lib/steel/Steel.FractionalAnchoredPreorder.fst
- lib/steel/Steel.FractionalPermission.fst
- lib/steel/Steel.HigherReference.fst
See https://github.com/FStarLang/FStar/pull/3242
---
Hi! We're planning to change the interface of `FStar.Real` to only provide a logical axiomatization of real numbers, instead of the current seemingly-computable interface which does not make a lot of sense (or will not when we extend `FStar.Real` to make it more interesting).
This requires a few patches to make Steel work, hence this PR. Wondering if this seems sensible to you and there are any serious breakages outside this repo.
Thanks!
> FractionalPermission: Fixes for new F* real interface

- lib/steel/Steel.Effect.Common.fsti
- src/ocaml/plugin/generated/Steel_Effect_Common.ml
This should also preserve error ranges better.
--
This fixes the build after https://github.com/FStarLang/FStar/pull/3370. Sorry for not noticing earlier. It also makes re-raised exceptions preserve the original range, so I wonder if it improves error locations noticeably in Steel code.
> Steel.Effect.Common: update after changes to TacticFailure exception

- lib/steel/Steel.ST.HigherArray.fst
This is flaky and will break with an incoming F* PR, bump the rlimit.
> Steel.ST.HigherArray: bump rlimit

- src/ci/opam.Dockerfile
I think this should fix the OPAM CI, but it fails with something seemingly unrelated:
```
2024-08-26T00:09:42.6558328Z /home/opam/steel_tools/karamel/krmllib/dist/minimal/FStar_UInt128_Verified.h:10:10: fatal error: WindowsWorkaroundSigh.h: No such file or directory
2024-08-26T00:09:42.6560682Z    10 | #include "WindowsWorkaroundSigh.h"
2024-08-26T00:09:42.6561608Z       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```
> fixing missing packages in opam CI

- lib/steel/Steel.ST.Array.fst
- src/Makefile
- src/extraction/ExtractSteel.fst
- src/extraction/ExtractSteel.fsti
- src/extraction/ExtractSteelC.fst
- src/extraction/ExtractSteelC.fsti
- src/extraction/Makefile
- src/ocaml/plugin/generated/ExtractSteel.ml
- src/ocaml/plugin/generated/ExtractSteelC.ml
- src/ocaml/plugin/generated/Steel_Effect_Common.ml
- src/ocaml/plugin/generated/Steel_ST_GenElim1_Base.ml
- src/ocaml/plugin/generated/Steel_ST_GenElim_Base.ml
Fixes for F* PR https://github.com/FStarLang/FStar/pull/3557, needed since the extraction plugin is written against an internal API.
> Moving FStar->FStarC

- mk/plugin.mk
See https://github.com/FStarLang/FStar/pull/3640
> mk: Fix --already_cached '*', which fails in Windows

- Makefile
- include/steel/steel_full.h
- mk/boot.mk
- mk/common.mk
- share/steel/Makefile.include
- share/steel/examples/steel/OWGCounter/OWGCounterTest.ml
- share/steel/tests/krml/Makefile
- src/extraction/ExtractSteel.Krml.fst
- src/extraction/ExtractSteel.Krml.fsti
- src/extraction/ExtractSteel.ML.fst
- src/extraction/ExtractSteel.ML.fsti
- src/extraction/ExtractSteel.fsti
- src/extraction/ExtractSteelC.Krml.fst
- src/extraction/ExtractSteelC.Krml.fsti
- src/extraction/ExtractSteelC.fsti
- src/extraction/Extraction.fst.config.json
- src/extraction/Makefile
- src/proofs/steelc/Makefile
Follow up to #199. The F*->ML rules taking care of erasing invariants were mistakenly dropped by FStarLang/FStar#3557. This PR adds them back to the Steel plugin, in a standalone file. There is also a bit of cleanup for the ML->Krml extraction rules, which are now in better-named files.
Many thanks to @cmovcc for the report and investigation here.
> Fixing extraction

- lib/steel/Steel.Effect.Atomic.fsti
F* may infer the type of this equality to be the refined one, which would fail.
> Steel.Effect.Atomic: disambiguate type in equality

- lib/steel/Steel.Effect.Atomic.fsti
This is not actually needed. It did fail while I was working on F* PR https://github.com/FStarLang/FStar/pull/3841, but after a few changes, the original code behaves as before.
The equality is indeed between two different types, but they are refinements of the same base type. The unifier should just join the refinements.
This reverts commit fc35ec46065f46aa701145a2a312dc2a76002bf8.
> Revert "Steel.Effect.Atomic: disambiguate type in equality"

- lib/steel/Steel.Effect.Common.fsti
- lib/steel/Steel.ST.GenElim.Base.fsti
- lib/steel/Steel.ST.GenElim1.Base.fsti
This function has been deprecated for a while and should be removed. The old builtin term_eq had an interesting behavior of ignoring universe annotations and ascriptions, which Steel seem to rely on. F* added a new laxer term_eq function (https://github.com/FStarLang/FStar/pull/3936) that mimics this old behavior, but is completely implemented in userspace.
> Remove uses of term_eq_old and make sure to use new lax_term_eq
